apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress    
spec:
  ingressClassName: nginx
  rules:
  - host: app.service.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app-service
              port:
                number: 3000