name: CD

on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USERNAME: docker@cofares.es
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: app-helm

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: docker@cofares.es
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Build Docker image
        run: docker build -t dockercofares/${{ env.IMAGE_NAME }}:${{ github.sha }} .
      
      - name: Login Docker hub
        run: echo c0f4r3s_1 | docker login --username docker@cofares.es --password-stdin
      - name: Push Docker image
        run: docker push dockercofares/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update values.yaml
        run: |
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push